export const IPC_CHANNELS = {
	getEnvironment: "app:get-environment",
	configGet: "config:get",
	configSaveAgentCore: "config:save-agent-core",
	configSaveModel: "config:save-model",
	configDeleteModel: "config:delete-model",
	configTestModel: "config:test-model",
	configSaveCapability: "config:save-capability",
	configDeleteCapability: "config:delete-capability",
	configSaveAgent: "config:save-agent",
	configDeleteAgent: "config:delete-agent",
	configReset: "config:reset",
	getWorkspace: "workspace:get",
	chooseWorkspace: "workspace:choose",
	workspaceListFiles: "workspace:list-files",
	workspaceReadFile: "workspace:read-file",
	auditListLogs: "audit:list-logs",
	agentStartSession: "agent:start-session",
	agentStopSession: "agent:stop-session",
	agentGetSessionState: "agent:get-session-state",
	agentSendUserMessage: "agent:send-user-message",
	agentListAvailableTools: "agent:list-available-tools",
} as const;
